### ISSUE TITLE
Minimum Xcode version

### ISSUE THREAD

**Issue by cdjames** [janka102/MASM_OSX#1]
Any chance you could specify the minimum version of Xcode needed for this project in the readme?

**Comment by janka102** [comment]
I'm not sure of the minimum version it works with, but I added that I have used it with the latest version of both Xcode 6 and 7. If you can get it to work with earlier versions, let me know and I'll update the readme.

**Comment by cdjames** [comment]
Thanks! I've got it working on the last version of Xcode 5 (5.1.1). I had to change the OS X Deployment Target (in the project info pane) to 10.8 (my current OS) before doing anything, but then it worked.
