### ISSUE TITLE
Xcode can't hit breakpoint

### ISSUE THREAD

**Issue by why2000** [janka102/MASM_OSX#4]
Under Xcode 9.3.1, after trying to run some simple code with template.asm (for example just mov eax, 0, and _ byte 0 in .data), Xcode just skipped the breakpoint that is said in README, and finished with such a message:
* Warning: hit breakpoint while running function, skipping commands and conditions to prevent recursion.

Maybe this is an issue from my Xcode configs, but there seems to be no information about how to stop Xcode's skipping breakpoints automatically.

**Comment by why2000** [comment]
In fact after building, I can use lldb to add breakpoints at main using "br s --shlib targetname --name main", but when I try to add such a breakpoint in Xcode, it will sill show that warning and ignore all the breakpoints.
So for sure it's a problem with Xcode, but still don't know how to fix it...

**Comment by why2000** [comment]
Well this issue is solved by disable backtrace recording shown in the following:
* Product->scheme->Run->Options->Queue Debugging (the last line of "Option" page)
* disable the "enable backtrace recording"

**Comment by janka102** [comment]
Thanks for looking into this :+1: I've updated the readme.
